[package]
name = "check_elf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf_rs = { git = "https://github.com/vincenthouyi/elf_rs", rev = "d040e18b4cc6b87139f6856802e9dca3d298f726" }
